# Netlify Configuration File

# === Build Settings ===
[build]
# Specifies the build command to be executed by Netlify.
# 'npm run build' is commonly used to generate production-ready files.
command = "npm run build"

# Indicates the directory containing the files to be published after the build process.
# 'dist' is a common output directory for many frontend frameworks.
publish = "dist"

# === Custom Headers ===
# Applies custom HTTP headers to specific paths.
[[headers]]
# The path(s) to which these headers apply.
# This example targets all JavaScript files under the '/assets/' directory.
for = "/assets/*.js"
[headers.values]
# Sets the 'Content-Type' header to 'application/javascript' to ensure correct MIME type delivery.
"Content-Type" = "application/javascript"

# === Redirect Rules ===
# Implements URL redirect rules for your site.
[[redirects]]
# 'from' is the incoming path or pattern to match. '/*' matches all requests.
from = "/*"
# 'to' is the destination path for the redirect.
# '/index.html' is used for Single Page Applications (SPAs) to serve the main HTML file.
to = "/index.html"
# 'status' is the HTTP status code for the redirect.
# '200' (OK) is crucial for SPAs, as it performs a rewrite without changing the browser URL.
status = 200